### PR TITLE
API url generation for the snippet moved to block

### PR DESCRIPTION
**Pull request by bbakalov**
API URL generation for the snippet endpoint 'rest/V1/swell/session/snippet' moved to block

### CODE REVIEW

**Comment by bbakalov** [comment]
@pniel-cohen hello. Why have you closed it without any explanation?

**Comment by bbakalov** [comment]
Already checked that you added this fix in this commit. Good one
https://github.com/YotpoLtd/magento2-module-yotpo-loyalty/commit/0330423488e7bd6ac1fa05091319ecaa8fad0a82

**Comment by pniel-cohen** [comment]
@bbakalov ,
Sorry for not providing explanations. 
I did a little cleanup and closed all PRs that seemed to be old/irrelevant/conflicting or have been done already by someone at some point.
Thanks for your contribution, anyway.
--
Regardless of the above, I actually think it should be reverted and I probably wouldn't have merge it myself, since it was OK as if was (on all cases I've seen).

**Comment by pniel-cohen** [comment]
@bbakalov 
Sorry for not providing explanations. 
I did a little cleanup and closed all PRs that seemed to be old/irrelevant/conflicting or have been done already by someone at some point.
Thanks for your contribution, anyway.
Regardless of the above, I actually think it should be reverted and I probably wouldn't have merge it myself, since it was OK as if was (on all cases I've seen).

**Pull request closed without merging**
